// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/raiki02/EG/config"
	"github.com/raiki02/EG/internal/cache"
	"github.com/raiki02/EG/internal/controller"
	"github.com/raiki02/EG/internal/dao"
	"github.com/raiki02/EG/internal/ioc"
	"github.com/raiki02/EG/internal/middleware"
	"github.com/raiki02/EG/internal/mq"
	"github.com/raiki02/EG/internal/repo"
	"github.com/raiki02/EG/internal/router"
	"github.com/raiki02/EG/internal/server"
	"github.com/raiki02/EG/internal/service"
)

// Injectors from wire.go:

func InitApp() *server.Server {
	engine := ioc.InitGinHandler()
	conf := config.InitConf()
	client := ioc.InitRedis(conf)
	cacheCache := cache.NewCache(client)
	db := ioc.InitDB(conf)
	logger := ioc.Newlogger()
	userDao := dao.NewUserDao(db, logger)
	actDao := dao.NewActDao(db, logger, conf)
	postDao := dao.NewPostDao(db, logger, conf)
	commentDao := dao.NewCommentDao(db, logger)
	jwt := middleware.NewJwt(client, conf)
	ccnuService := service.NewCCNUService()
	imgUploader := service.NewImgUploader(conf)
	userRepo := repo.NewUserRepo(userDao, cacheCache)
	activityRepo := repo.NewActivityRepo(actDao, cacheCache)
	postRepo := repo.NewPostRepo(postDao, cacheCache)
	interactionDao := dao.NewInteractionDao(db, commentDao, userDao, actDao, postDao, logger)
	interactionRepo := repo.NewInteractionRepo(interactionDao, userRepo, activityRepo, postRepo)
	mqHdl := mq.NewMQ(client)
	auditorRepository := dao.NewAuditorRepo(db, logger)
	auditorService := service.NewAuditorService(auditorRepository, logger, conf)
	activityService := service.NewActivityService(activityRepo, userRepo, logger, interactionRepo, mqHdl, auditorService)
	postService := service.NewPostService(postRepo, userRepo, logger, auditorService)
	userService := service.NewUserService(userRepo, activityRepo, postRepo, jwt, ccnuService, imgUploader, activityService, postService, logger, conf)
	userController := controller.NewUserController(engine, userService, logger)
	userRouter := router.NewUserRouter(engine, userController, jwt)
	actController := controller.NewActController(activityService, imgUploader, logger)
	actRouter := router.NewActRouter(engine, actController, jwt)
	postController := controller.NewPostController(postService, logger)
	postRouter := router.NewPostRouter(engine, postController, jwt)
	actPostCommentGetter := service.NewActPostCommentGetter(activityRepo, postRepo, commentDao)
	commentService := service.NewCommentService(commentDao, userRepo, interactionRepo, logger, mqHdl, actPostCommentGetter)
	commentController := controller.NewCommentController(commentService, logger)
	commentRouter := router.NewCommentRouter(commentController, engine, jwt)
	feedDao := dao.NewFeedDao(db, logger)
	feedService := service.NewFeedService(feedDao, mqHdl, userRepo, logger)
	feedController := controller.NewFeedController(feedService, logger)
	feedRouter := router.NewFeedRouter(feedController, engine, jwt)
	interactionService := service.NewInteractionService(interactionRepo, mqHdl, logger, actPostCommentGetter)
	interactionController := controller.NewInteractionController(interactionService, logger)
	interactionRouter := router.NewInteractionRouter(engine, interactionController, jwt)
	cors := middleware.NewCors(engine)
	callbackAuditorService := service.NewCallbackAuditor(auditorRepository)
	callbackAuditorController := controller.NewCallbackAuditorController(engine, callbackAuditorService, conf)
	routerRouter := router.NewRouter(engine, userRouter, actRouter, postRouter, commentRouter, feedRouter, interactionRouter, cors, callbackAuditorController)
	serverServer := server.NewServer(routerRouter, logger)
	return serverServer
}
