// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/raiki02/EG/config"
	"github.com/raiki02/EG/internal/cache"
	"github.com/raiki02/EG/internal/dao"
	"github.com/raiki02/EG/internal/handler"
	"github.com/raiki02/EG/internal/ioc"
	"github.com/raiki02/EG/internal/middleware"
	"github.com/raiki02/EG/internal/mq"
	"github.com/raiki02/EG/internal/repo"
	"github.com/raiki02/EG/internal/server"
	"github.com/raiki02/EG/internal/service"
)

// Injectors from wire.go:

func InitApp() *server.Server {
	engine := ioc.InitGinHandler()
	cors := middleware.NewCors(engine)
	conf := config.InitConf()
	db := ioc.InitDB(conf)
	loggerSet := ioc.NewLoggerSet()
	userDao := dao.NewUserDao(db, loggerSet)
	client := ioc.InitRedis(conf)
	multiLevelCache := cache.NewCache(client)
	userRepo := repo.NewUserRepo(userDao, multiLevelCache)
	actDao := dao.NewActDao(db, loggerSet, conf)
	activityRepo := repo.NewActivityRepo(actDao, multiLevelCache)
	postDao := dao.NewPostDao(db, loggerSet, conf)
	postRepo := repo.NewPostRepo(postDao, multiLevelCache)
	jwt := middleware.NewJwt(client, conf)
	ccnuService := service.NewCCNUService()
	imgUploader := service.NewImgUploader(conf)
	commentDao := dao.NewCommentDao(db, loggerSet)
	interactionDao := dao.NewInteractionDao(db, commentDao, userDao, actDao, postDao, loggerSet)
	interactionRepo := repo.NewInteractionRepo(interactionDao, userRepo, activityRepo, postRepo)
	mqHdl := mq.NewMQ(client)
	auditorRepository := dao.NewAuditorRepo(db, loggerSet)
	auditorService := service.NewAuditorService(auditorRepository, loggerSet, conf)
	activityService := service.NewActivityService(activityRepo, userRepo, loggerSet, interactionRepo, mqHdl, auditorService)
	postService := service.NewPostService(postRepo, userRepo, loggerSet, auditorService)
	userService := service.NewUserService(userRepo, activityRepo, postRepo, jwt, ccnuService, imgUploader, activityService, postService, loggerSet, conf)
	userHandler := handler.NewUserHandler(engine, userService, jwt, loggerSet)
	actHandler := handler.NewActHandler(engine, activityService, imgUploader, loggerSet, jwt)
	postHandler := handler.NewPostHandler(engine, postService, jwt, loggerSet)
	subjectGetter := service.NewSubjectGetter(activityRepo, postRepo, commentDao)
	commentService := service.NewCommentService(commentDao, userRepo, interactionRepo, loggerSet, mqHdl, subjectGetter)
	commentHandler := handler.NewCommentHandler(engine, commentService, jwt, loggerSet)
	feedDao := dao.NewFeedDao(db, loggerSet)
	feedService := service.NewFeedService(feedDao, mqHdl, userRepo, loggerSet)
	feedHandler := handler.NewFeedHandler(engine, feedService, jwt, loggerSet)
	interactionService := service.NewInteractionService(interactionRepo, mqHdl, loggerSet, subjectGetter)
	interactionHandler := handler.NewInteractionHandler(engine, interactionService, jwt, loggerSet)
	callbackAuditorService := service.NewCallbackAuditor(auditorRepository)
	callbackAuditorHandler := handler.NewCallbackAuditorHandler(engine, callbackAuditorService, conf, loggerSet)
	handlerHandler := handler.NewHandler(engine, cors, userHandler, actHandler, postHandler, commentHandler, feedHandler, interactionHandler, callbackAuditorHandler)
	serverServer := server.NewServer(handlerHandler, loggerSet)
	return serverServer
}
