// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/raiki02/EG/config"
	"github.com/raiki02/EG/internal/cache"
	"github.com/raiki02/EG/internal/dao"
	"github.com/raiki02/EG/internal/handler"
	"github.com/raiki02/EG/internal/ioc"
	"github.com/raiki02/EG/internal/middleware"
	"github.com/raiki02/EG/internal/mq"
	"github.com/raiki02/EG/internal/repo"
	"github.com/raiki02/EG/internal/server"
	"github.com/raiki02/EG/internal/service"
	"github.com/raiki02/EG/pkg/logger"
)

import (
	_ "github.com/raiki02/EG/docs"
)

// Injectors from wire.go:

func InitApp() *server.Server {
	engine := ioc.InitGinHandler()
	cors := middleware.NewCors(engine)
	conf := config.InitConf()
	db := ioc.InitDB(conf)
	loggerSet := logger.NewLoggerSet()
	userDao := dao.NewUserDao(db, loggerSet)
	client := ioc.InitRedis(conf)
	multiLevelCache := cache.NewCache(client)
	userRepo := repo.NewUserRepo(userDao, multiLevelCache)
	actDao := dao.NewActDao(db, conf, loggerSet)
	activityRepo := repo.NewActivityRepo(actDao, multiLevelCache)
	postDao := dao.NewPostDao(db, conf, loggerSet)
	postRepo := repo.NewPostRepo(postDao, multiLevelCache)
	interactionDao := dao.NewInteractionDao(db, loggerSet)
	interactionRepo := repo.NewInteractionRepo(interactionDao, userRepo, activityRepo, postRepo)
	jwt := middleware.NewJwt(client, conf)
	ccnuService := service.NewCCNUService()
	imgUploader := service.NewImgUploader(conf)
	mqHdl := mq.NewMQ(client)
	auditorRepository := dao.NewAuditorRepo(db, loggerSet)
	auditorService := service.NewAuditorService(auditorRepository, conf, loggerSet)
	activityService := service.NewActivityService(activityRepo, userRepo, interactionRepo, mqHdl, auditorService, loggerSet)
	postService := service.NewPostService(postRepo, userRepo, interactionRepo, auditorService, loggerSet)
	userService := service.NewUserService(userRepo, activityRepo, postRepo, interactionRepo, jwt, ccnuService, imgUploader, activityService, postService, loggerSet, conf)
	userHandler := handler.NewUserHandler(engine, userService, jwt, loggerSet)
	actHandler := handler.NewActHandler(engine, activityService, imgUploader, jwt, loggerSet)
	postHandler := handler.NewPostHandler(engine, postService, jwt, loggerSet)
	commentDao := dao.NewCommentDao(db, loggerSet)
	subjectGetter := service.NewSubjectGetter(activityRepo, postRepo, commentDao)
	commentService := service.NewCommentService(commentDao, userRepo, interactionRepo, mqHdl, subjectGetter, loggerSet)
	commentHandler := handler.NewCommentHandler(engine, commentService, jwt, loggerSet)
	feedDao := dao.NewFeedDao(db, loggerSet)
	feedService := service.NewFeedService(feedDao, mqHdl, userRepo, loggerSet)
	feedHandler := handler.NewFeedHandler(engine, feedService, jwt, loggerSet)
	interactionService := service.NewInteractionService(interactionRepo, mqHdl, subjectGetter, loggerSet)
	interactionHandler := handler.NewInteractionHandler(engine, interactionService, jwt, loggerSet)
	callbackAuditorService := service.NewCallbackAuditor(auditorRepository)
	callbackAuditorHandler := handler.NewCallbackAuditorHandler(engine, callbackAuditorService, conf, loggerSet)
	handlerHandler := handler.NewHandler(engine, cors, userHandler, actHandler, postHandler, commentHandler, feedHandler, interactionHandler, callbackAuditorHandler)
	auditorUploadWorker := service.NewAuditorUploadWorker(activityRepo, auditorService, loggerSet)
	serverServer := server.NewServer(handlerHandler, auditorUploadWorker)
	return serverServer
}
